### ISSUE TITLE
Quiz 1: HTML/CSS Assessment

### ISSUE THREAD

**Issue by micjamking** [kcc-nma-art258/assignments#24]
Render the pricing table image in HTML/CSS, including the product title, prices, details, and action items (buttons).

The styling of the page and pricing table should match the following screenshot: 

![Pricing Table (PNG)](https://d13yacurqjgara.cloudfront.net/users/25867/screenshots/842947/attachments/210494/pricing-table-01.jpg)

Fork the following project: [CodePen - Pricing Table](http://codepen.io/micjamking/pen/669f0200762bd219b2d26e9864de80d7/)

Please post a link to your Codepen example as a comment below.

[Live Coding Example](http://codepen.io/micjamking/professor/f5a3bbbd40f0cc380fa7b093effb7bd4/)

_This will be graded for completion. My goal is to see where everyone's skill level is to start, so as long as you make an honest attempt you'll pass._

**Comment by githubhyelalee** [comment]
http://codepen.io/githubhyelalee/details/mJNaQN/

**Comment by joshuayclements** [comment]
http://codepen.io/joshuayclements/pen/gaYPmE?editors=110

**Comment by lusead** [comment]
http://codepen.io/lusead/pen/vOovvw?editors=110

**Comment by kalenakudelima** [comment]
http://codepen.io/kalenakudelima/pen/GpKvYa

**Comment by Yeona** [comment]
http://codepen.io/Yeona/pen/BNXeNz

**Comment by alohavolha** [comment]
http://codepen.io/alohavolha/pen/GJVPPK

**Comment by normaucore58** [comment]
http://codepen.io/normaucore58/pen/jPgdjp

**Comment by myoung0724** [comment]
http://codepen.io/myoung0724/pen/QjLqwG

**Comment by sam-campos** [comment]
http://codepen.io/sam-campos/details/NGKEoe/

**Comment by Ressa808** [comment]
http://codepen.io/Srwada808/pen/VvwQpR

**Comment by TVS86** [comment]
http://codepen.io/TVS86/pen/BooZxz
